import {cp, mkdir, readFile, writeFile} from 'node:fs/promises';
await mkdir('cloudflare/public/vendor', {recursive:true});
await cp('public','cloudflare/public',{recursive:true});
await cp('node_modules/exifr/dist/full.umd.js','cloudflare/public/vendor/exifr.js');
await cp('cloudflare/client.js','cloudflare/public/edge-client.js');
let html=await readFile('public/index.html','utf8');
html=html.replace('<script src="app.js', '<script src="vendor/exifr.js"></script><script src="edge-client.js"></script>\n  <script src="app.js');
await writeFile('cloudflare/public/index.html',html);
let js=await readFile('public/app.js','utf8');
const start=js.indexOf('async function extractPhotoMetadata(file) {');
const end=js.indexOf('\nfunction titleFromFilename',start);
if(start<0||end<0) throw Error('EXIF integration point missing');
js=js.slice(0,start)+'async function extractPhotoMetadata(file) { return window.VIVAD_EDGE.metadata(file); }\n'+js.slice(end);
const original="fetch('/api/items', { method: 'POST', body: buildFormData(files[index]) })";
if(!js.includes(original)) throw Error('Upload integration point missing');
js=js.replace(original,'window.VIVAD_EDGE.submit(buildFormData(files[index]))');
js=js.replaceAll("fetch('/api/items/'", "window.VIVAD_EDGE.mutate('/api/items/'");
await writeFile('cloudflare/public/app.js',js);
console.log('Cloudflare assets built');
