CREATE TABLE IF NOT EXISTS records (id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT NOT NULL, upload_token TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS uploads (token TEXT PRIMARY KEY, object_name TEXT NOT NULL, data TEXT NOT NULL, size INTEGER NOT NULL, mime TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS quotas (day TEXT PRIMARY KEY, count INTEGER NOT NULL, bytes INTEGER NOT NULL);
